name: 'Logseq Publish'
description: 'Publish your Logseq Graph'
inputs:
  dest:
    description: 'export destination'
    required: true
    default: 'www'
branding:
  icon: 'arrow-up-circle'  
  color: 'green'
runs:
  using: "composite"
  steps:
    - run: |
        curl https://raw.githubusercontent.com/pengx17/logseq-publish/main/Dockerfile.exec -o Dockerfile
        docker build -t tmp .
        container_id=$(docker create tmp)
        docker cp $container_id:/home/logseq/graph-www ${{ inputs.dest }}
        docker rm $container_id
        rm -f Dockerfile
      shell: bash
