name: "Logseq Publish"
description: "Publish your Logseq Graph"
inputs:
  dest:
    description: "export destination"
    required: true
    default: "www"
  version:
    description: >
      Logseq version to use. Note, not all version are supported.
      Use "master" if you are not sure what to put here
    required: true
    default: "master"
branding:
  icon: "arrow-up-circle"
  color: "green"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: '18'
    - uses: DeLaGuardo/setup-clojure@3.7
    - name: Checkout Logseq code
      uses: actions/checkout@v2
      with:
        repository: "logseq/logseq"
        ref: ${ inputs.version }
        path: "logseq"
    - name: Build Logseq static
      working-directory: "logseq"
      shell: bash
      run: |
        yarn
        yarn release
        mv ./static ../public
    - name: Install pnpm
      shell: bash
      run: |
        npm install -g pnpm
    - name: Install deps
      shell: bash
      run: |
        pnpm i
    - name: Install static
      working-directory: "public/static"
      shell: bash
      run: |
        yarn install
        yarn rebuild:better-sqlite3
    - name: Build graph
      shell: bash
      run: |
        xvfb-run node publish.mjs -p graph
