name: Build-Docker

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 16 * * *' # run at 2 AM UTC
jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build Docker
        run: |
          docker build -t ghcr.io/pengx17/logseq-publish:latest .

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image
        run: docker push ghcr.io/pengx17/logseq-publish:latest
