name: Build-Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Logseq branch tag"
        default: "nightly"
        required: true
        type: string

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build Docker
        run: |
          echo Build Tag ${{ inputs.tag }}
          docker build --build-arg LOGSEQ_TAG=${{ inputs.tag }} -t ghcr.io/pengx17/logseq-publish:${{ inputs.tag }} .

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image
        run: docker push ghcr.io/pengx17/logseq-publish:latest
