name: Nightly Build

on:
  workflow_dispatch:
  schedule: # Every day
    - cron: '* */23 * * *'

jobs:
  call-build-docker:
    uses: ./.github/workflows/build-docker.yml
    with:
      tag: nightly
      publish_tag: nightly
