name: Nightly Build

on:
  schedule: # Every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  call-build-docker:
    uses: ./.github/workflows/build-docker.yml
    with:
      tag: nightly
      publish_tag: nightly
