name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Logseq Publish
        uses: ./
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: www
      - uses: actions/upload-artifact@v2
        with:
          path: trace.zip
